version: "3"

services:
  odoo:
    image: odoo-local:dev
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        # change the ODOO_BASE_IMAGE variable to whatever docker image you want to use
        - ODOO_BASE_IMAGE=odoo:15
    command: --dev all
    depends_on:
      - db
    environment:
      - TZ=Etc/UTC
      - PYTHONUNBUFFERED=1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - odoo-data:/var/lib/odoo
      - ../:/mnt/odoo-dev-env/
    networks:
      - odoo-dev

  db:
    image: postgres:13
    environment:
      - TZ=Etc/UTC
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - POSTGRES_DB=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata
    networks:
      - odoo-dev

  pgadmin:
    image: dpage/pgadmin4:latest
    entrypoint: >
      sh -c "
        cp /var/lib/pgadmin/pgadmin4.db.template /var/lib/pgadmin/pgadmin4.db &&
        chmod 600 /var/lib/pgadmin/pgadmin4.db &&
        exec /entrypoint.sh
      "
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=PgAdminPW!
    ports:
      - "8080:80"
    volumes:
      - ./pgadmin4.db:/var/lib/pgadmin/pgadmin4.db.template
    networks:
      - odoo-dev

volumes:
  odoo-data:
  db-data:

networks:
  odoo-dev:
    driver: bridge
